wandb_version: 1

activation:
  value: softmax
batch_size:
  value: 50
dense:
  value: 256
dropout:
  value: 0.5
learning_rate:
  value: 3.0e-05
optimizer:
  value: rmsprop
pretrain_net:
  value: inception
