wandb_version: 1

activation:
  value: selu
batch_size:
  value: 20
dense:
  value: 1024
dropout:
  value: 0.5
learning_rate:
  value: 0.01
optimizer:
  value: rmsprop
pretrain_net:
  value: inception
