wandb_version: 1

activation:
  value: softmax
batch_size:
  value: 50
dense:
  value: 1024
dropout:
  value: 0.2
learning_rate:
  value: 0.0001
optimizer:
  value: rmsprop
pretrain_net:
  value: inception
