wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1655393232
    t:
      1:
      - 3
      - 5
      - 53
      - 55
      2:
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      4: 3.9.12
      5: 0.12.18
      8:
      - 1
      - 5
activation:
  desc: null
  value: softmax
batch_size:
  desc: null
  value: 50
dense:
  desc: null
  value: 1024
dropout:
  desc: null
  value: 0.2
learning_rate:
  desc: null
  value: 0.0001
optimizer:
  desc: null
  value: rmsprop
pretrain_net:
  desc: null
  value: inception
