wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1655263577
    t:
      1:
      - 3
      - 5
      - 53
      - 55
      2:
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      4: 3.9.12
      5: 0.12.18
      8:
      - 5
batch_size:
  desc: null
  value: 65
dense:
  desc: null
  value: 714
drop_out:
  desc: null
  value: 0.7368340338491407
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 24
learning_rate:
  desc: null
  value: 0.00408163910033912
optimizer:
  desc: null
  value: rmsprop
